---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: pod - fields - volumes (secret)
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
  - ../_values/vaultstaticsecret_main_default.yaml
set:
  secrets:
    mySettings:
      stringData:
        test: testvalue
tests:
  - it: secret persistence type should pass
    set:
      persistence:
        secret:
          type: secret
          name: mySettings
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: secret
            secret:
              secretName: mySettings

  - it: secret persistence type with name template should pass
    set:
      persistence:
        secret:
          type: secret
          name: "{{ .Release.Name | lower }}-config"
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: secret
            secret:
              secretName: release-name-config

  - it: secret persistence type with identifier reference should pass
    set:
      persistence:
        secret:
          type: secret
          identifier: mySettings
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: secret
            secret:
              secretName: release-name


  - it: vaultStaticSecret persistence should support optional and items
    set:
      persistence:
        vault:
          type: vaultStaticSecret
          identifier: main
          optional: true
          items:
            - key: secret-key
              path: secret-path
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: vault
            secret:
              secretName: release-name
              optional: true
              items:
                - key: secret-key
                  path: secret-path

  - it: vaultStaticSecret persistence type with identifier should resolve to vault secret name with forceRename
    set:
      vaultStaticSecrets:
        main:
          forceRename: test
      persistence:
        vault:
          enabled: true
          type: vaultStaticSecret
          identifier: main
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: vault
            secret:
              secretName: test

  - it: vaultStaticSecret persistence should support optional and items with forceRename
    set:
      vaultStaticSecrets:
        main:
          forceRename: test
      persistence:
        vault:
          type: vaultStaticSecret
          identifier: main
          optional: true
          items:
            - key: secret-key
              path: secret-path
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.spec.volumes[0]
          value:
            name: vault
            secret:
              secretName: test
              optional: true
              items:
                - key: secret-key
                  path: secret-path
