---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: "pod - metadata - annotations"
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: default pod annotations
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - notExists:
          path: spec.template.metadata.annotations

  - it: pod annotations from defaultPodOptions should be included
    set:
      defaultPodOptions.annotations:
        defaultPodOptionsAnnotation: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - isSubset:
          path: spec.template.metadata.annotations
          content:
            defaultPodOptionsAnnotation: test

  - it: pod annotations from pod options should be included
    set:
      controllers.main.pod.annotations:
        podOptionsAnnotation: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - isSubset:
          path: spec.template.metadata.annotations
          content:
            podOptionsAnnotation: test

  - it: pod annotations from global annotations should not be included by default
    set:
      global.annotations:
        globalAnnotation: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - isNotSubset:
          path: spec.template.metadata.annotations
          content:
            globalAnnotation: test

  - it: pod annotations from global annotations should be included when requested
    set:
      global:
        propagateGlobalMetadataToPods: true
        annotations:
          globalAnnotation: test
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - isSubset:
          path: spec.template.metadata.annotations
          content:
            globalAnnotation: test

  - it: configMap checksum should be included in pod annotations when enabled
    set:
      configMaps:
        config:
          enabled: true
          includeInChecksum: true
          data:
            test: value 1
        test_default_enabled:
          includeInChecksum: true
          data:
            test: value 1
        test_not_in_checksum:
          includeInChecksum: false
          data:
            test: value 1
        test_disabled:
          enabled: false
          data:
            test: value 1
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.metadata.annotations
          value:
            checksum/configMaps: 66d23d7a53c4e2a523ba85a969696b4ebb78ec5d79ab9c12c210c1569f48511b

  - it: configMap checksum from folder should be included in pod annotations when enabled
    set:
      configMaps:
        config:
          enabled: true
          includeInChecksum: true
          data:
            test: value 1
        test_enabled:
          includeInChecksum: true
          includeChecksumInControllers:
            - main
          data:
            test: value 1
        test_not_in_checksum:
          includeInChecksum: false
          data:
            test: value 1
        test_not_in_controllers:
          includeInChecksum: true
          includeChecksumInControllers:
            - other-controller
          data:
            test: value 1
        test_disabled:
          enabled: false
          data:
            test: value 1
      configMapsFromFolder:
        enabled: true
        basePath: testFiles
        configMapsOverrides:
          escaped:
            fileAttributeOverrides:
              test_2.yaml:
                escaped: true
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.metadata.annotations
          value:
            checksum/configMaps: b32d6c26c2c93a282b42e09c7a6ef7c2d6a73153afa3cb5dedd0d3031381322f

  - it: secret checksum should be included in pod annotations when enabled
    set:
      secrets:
        secret_1:
          includeInChecksum: true
          stringData:
            test: value 1
        secret_2:
          includeInChecksum: true
          includeChecksumInControllers:
            - main
          stringData:
            test_1: value {{ 1 }}
            test_2: value 2
        test_not_in_checksum:
          includeInChecksum: false
          stringData:
            test: value 1
        test_not_in_controllers:
          includeInChecksum: true
          includeChecksumInControllers:
            - other-controller
          stringData:
            test: value 1
        test_disabled:
          enabled: false
          stringData:
            test: value 1
    documentSelector:
      path: $[?(@.kind == "Deployment")].metadata.name
      value: release-name
    asserts:
      - equal:
          path: spec.template.metadata.annotations
          value:
            checksum/secrets: cd4e5076088172611ca1c43c659a275232d9eeb887acc20575ac141038b9aacb
