---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 4.6.1
kubeVersion: ">=1.28.0-0"
keywords:
  - common
  - library
home: https://github.com/TilloTech/tillo-platform-helm-library/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
  - name: platform-team
sources:
  - https://github.com/TilloTech/tillo-platform-helm-library
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: |-
        Add support for Vault CRDs.
    - kind: added
      description: |-
        Add support for configuring supplementalGroupsPolicy in Pod SecurityContext.
    - kind: fixed
      description: |-
        Fixed checksum annotation when templates are used in ConfigMaps and Secrets.
