---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: persistence - validations
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
tests:
  - it: configmap persistence type with invalid identifier reference should fail
    set:
      persistence:
        configmap:
          type: configMap
          identifier: doesNotExist
    asserts:
      - failedTemplate:
          errorMessage: "No configmap found with this identifier. (persistence item 'configmap', identifier 'doesNotExist')"

  - it: secret persistence type with invalid identifier reference should fail
    set:
      persistence:
        secret:
          type: secret
          identifier: doesNotExist
    asserts:
      - failedTemplate:
          errorMessage: "No secret found with this identifier. (persistence item 'secret', identifier 'doesNotExist')"

  - it: vaultStaticSecret persistence type with invalid identifier reference should fail
    set:
      persistence:
        static:
          type: vaultStaticSecret
          identifier: doesNotExist
    asserts:
      - failedTemplate:
          errorMessage: "No vaultStaticSecret found with this identifier. (persistence item 'static', identifier 'doesNotExist')"

  - it: vaultDynamicSecret persistence type with invalid identifier reference should fail
    set:
      persistence:
        dynamic:
          type: vaultDynamicSecret
          identifier: doesNotExist
    asserts:
      - failedTemplate:
          errorMessage: "No vaultDynamicSecret found with this identifier. (persistence item 'dynamic', identifier 'doesNotExist')"
